---
# setup nginx

# Check whether the web configuration needs to be regenerated

- name: omero web | check OMERO.web symlink timestamp
  stat:
    follow: no
    path: "{{ omero_web_basedir }}/{{ omero_web_symlink }}"
  register: omero_web_symlink_st

- name: omero web | check nginx config timestamp
  stat:
    path: /etc/nginx/conf.d/omero-web.conf
  register: omero_web_nginx_config_st

- name: omero web | check if nginx config update is needed
  set_fact:
    omero_web_nginx_update_needed: >
      {{ (not omero_web_nginx_config_st.stat.exists) or
         (omero_web_nginx_config_st.stat.ctime < omero_web_symlink_st.stat.ctime)
      }}

- debug:
    msg: "Nginx configuration deploy or update needed? {{ omero_web_nginx_update_needed }}"

# This will generate a warning about running su, ignore it since we need to run as root for the redirection
- name: omero web | generate nginx config
  become: yes
  shell: >
    su {{ omero_web_system_user }} -lc
    "{{ omero_web_basedir }}/venv/bin/python
    {{ omero_web_basedir }}/{{ omero_web_symlink }}/bin/omero web
    config nginx"
    > /etc/nginx/conf.d/omero-web.conf
  when: omero_web_nginx_update_needed
  notify: restart nginx

- name: omero web | nginx remove system defaults
  become: yes
  replace:
    backup: yes
    dest: /etc/nginx/nginx.conf
    regexp: '80\s*default_server\s*;'
    replace: '80; # default_server;'
  notify: restart nginx

- name: omero web | enable nginx
  become: yes
  service:
    enabled: yes
    name: nginx
    state: started

# SELinux should be handled by openmicroscopy.omero-web-runtime
